[versions]
#App deps
lombok = "1.18.44"
jetbrains-annotation = "26.1.0"
slf4j = "2.1.0-alpha1"

# Database deps
doma = "3.12.0"

# JMH Libraries
jmh-lib = "1.37"

#Gradle Plugin
gradle-versions = "0.52.0"
jmh-pl = "0.7.3"
doma-compile = "4.0.3"
doma-codegen = "3.2.1"
graalvm = "1.1.2"
runTask = "2.2.3"


[libraries]
#App deps
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotation" }
slf4j = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }

# Database deps
doma-core = { module = "org.seasar.doma:doma-core", version.ref = "doma" }
doma-processor = { module = "org.seasar.doma:doma-processor", version.ref = "doma" }

# JMH Libraries
jmh-core = { module = "org.openjdk.jmh:jmh-core", version.ref = "jmh-lib" }
jmh-apt = { module = "org.openjdk.jmh:jmh-generator-annprocess", version.ref = "jmh-lib" }
jmh-bytecode = { module = "org.openjdk.jmh:jmh-generator-bytecode", version.ref = "jmh-lib" }

#Gradle Plugin
gradle-versions = { module = "com.github.ben-manes:gradle-versions-plugin", version.ref = "gradle-versions" }
jmh-pl = { module = "me.champeau.jmh:me.champeau.jmh.gradle.plugin", version.ref = "jmh-pl" }
doma-compile = { module = "org.domaframework.doma.compile:org.domaframework.doma.compile.gradle.plugin", version.ref = "doma-compile" }
doma-codegen = { module = "org.domaframework.doma.codegen:org.domaframework.doma.codegen.gradle.plugin", version.ref = "doma-codegen" }
graalvm = { module = "org.graalvm.buildtools.native:org.graalvm.buildtools.native.gradle.plugin", version.ref = "graalvm" }
runTask = { module = "xyz.jpenilla:run-task", version.ref = "runTask" }
